export const Permissions = {
  VIEW_ALL_PRODUCT_RECORDS: "VIEW_ALL_PRODUCT_RECORDS",
  VIEW_ALL_PRODUCT_REQUESTS: "VIEW_ALL_PRODUCT_REQUESTS",
  RE_DE_ACTIVATE_PRODUCT: "RE_DE_ACTIVATE_PRODUCT",
  AUTHORIZE_CREATION_OR_MODIFICATION_REQUESTS:
    "AUTHORIZE_CREATION_OR_MODIFICATION_REQUESTS",
  AUTHORIZE_REACTIVATION_OR_DEACTIVATION_REQUESTS:
    "AUTHORIZE_REACTIVATION_OR_DEACTIVATION_REQUESTS",
  CREATE_BULK_PRODUCT: "CREATE_BULK_PRODUCT",
  CREATE_SINGLE_PRODUCT: "CREATE_SINGLE_PRODUCT",
} as const;
