export const Permissions = {
  VIEW_ALL_BRANCH_RECORDS: "VIEW_ALL_BRANCH_RECORDS",
  VIEW_ALL_BRANCH_REQUESTS: "VIEW_ALL_BRANCH_REQUESTS",
  RE_DE_ACTIVATE_BRANCH: "RE_DE_ACTIVATE_BRANCH",
  AUTHORIZE_CREATION_OR_MODIFICATION_REQUESTS:
    "AUTHORIZE_CREATION_OR_MODIFICATION_REQUESTS",
  AUTHORIZE_REACTIVATION_OR_DEACTIVATION_REQUESTS:
    "AUTHORIZE_REACTIVATION_OR_DEACTIVATION_REQUESTS",
  CREATE_BULK_BRANCH: "CREATE_BULK_BRANCH",
  CREATE_SINGLE_BRANCH: "CREATE_SINGLE_BRANCH",
} as const;
