// import React from 'react'
// import { fireEvent, render, screen,  } from "@testing-library/react";
// import AccountingEntriesAndEvents, {InputDivs} from '../../../../../components/pages/term-deposit/forms/accounting-entries-and-events'

// // Generated by CodiumAI

// describe('AccountingEntriesAndEvents', () => {
//     // Mock the function passed as a prop
    
//   });
